"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-insecure-secret-key-dev-only-insecure-secret-key")
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"
ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]
if not DEBUG and SECRET_KEY == "dev-only-insecure-secret-key-dev-only-insecure-secret-key":
    raise RuntimeError("DJANGO_SECRET_KEY must be set in production")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "django_celery_beat",
    "corsheaders",
    "channels",

    # Local apps
    "users",
    "clients",
    "orders",
    "inventory",
    "notifications",
    "reports",
    "system_settings",
    "audit",
    "security",
    "realtime",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "security.middleware.SecurityHeadersMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_cors_origins_raw = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "http://localhost:5173")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_raw.split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

_channel_layer = (os.environ.get("CHANNEL_LAYER") or "").strip().lower()
if _channel_layer == "redis":
    # Production-ready вариант для WebSocket/Channels (работает и с несколькими процессами).
    # Требует зависимости channels_redis и доступного Redis.
    redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379/1")
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [redis_url]},
        }
    }
else:
    # Dev-only вариант.
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "master_print"),
        "USER": os.environ.get("POSTGRES_USER", "master_print"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "master_print"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": int(os.environ.get("POSTGRES_PORT", "5432")),
        "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

DEFAULT_PAGINATION_PAGE_SIZE = int(os.environ.get("DEFAULT_PAGINATION_PAGE_SIZE", "50"))


def _safe_drf_rate(env_name: str, default: str) -> str:
    raw = (os.environ.get(env_name, default) or "").strip().lower()
    if "/" not in raw:
        return default
    num, period = raw.split("/", 1)
    if not num.isdigit():
        return default
    period = period.strip()
    if not period or period[0] not in ("s", "m", "h", "d"):
        return default
    return f"{int(num)}/{period}"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": DEFAULT_PAGINATION_PAGE_SIZE,
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": _safe_drf_rate("DRF_THROTTLE_ANON", "60/min"),
        "user": _safe_drf_rate("DRF_THROTTLE_USER", "300/min"),
        "login": _safe_drf_rate("DRF_THROTTLE_LOGIN", "5/m"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_MINUTES", "30"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_DAYS", "7"))
    ),
}

JWT_ACCESS_COOKIE_NAME = os.environ.get("JWT_ACCESS_COOKIE_NAME", "mp_access_token")
JWT_REFRESH_COOKIE_NAME = os.environ.get("JWT_REFRESH_COOKIE_NAME", "mp_refresh_token")
JWT_COOKIE_PATH = os.environ.get("JWT_COOKIE_PATH", "/")
JWT_COOKIE_DOMAIN = os.environ.get("JWT_COOKIE_DOMAIN") or None
JWT_COOKIE_SAMESITE = os.environ.get("JWT_COOKIE_SAMESITE", "Strict")
JWT_COOKIE_SECURE = os.environ.get("JWT_COOKIE_SECURE", "0" if DEBUG else "1") == "1"
JWT_ACCESS_COOKIE_AGE_SECONDS = int(
    os.environ.get(
        "JWT_ACCESS_COOKIE_AGE_SECONDS",
        str(int(SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"].total_seconds())),
    )
)
JWT_REFRESH_COOKIE_AGE_SECONDS = int(
    os.environ.get(
        "JWT_REFRESH_COOKIE_AGE_SECONDS",
        str(int(SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"].total_seconds())),
    )
)

# Security headers / cookies (enabled for non-debug by default, can be overridden by env)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "1") == "1"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "1") == "1"
    SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "1") == "1"
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
REFERRER_POLICY = "strict-origin-when-cross-origin"

_csp_default_src = os.environ.get("DJANGO_CSP_DEFAULT_SRC", "'self'")
_csp_script_src = os.environ.get("DJANGO_CSP_SCRIPT_SRC", "'self'")
_csp_style_src = os.environ.get("DJANGO_CSP_STYLE_SRC", "'self'")
CSP_DEFAULT_SRC = tuple(s for s in _csp_default_src.split(" ") if s)
CSP_SCRIPT_SRC = tuple(s for s in _csp_script_src.split(" ") if s)
CSP_STYLE_SRC = tuple(s for s in _csp_style_src.split(" ") if s)

# Upload security limits for print files.
UPLOAD_MAX_FILE_SIZE_BYTES = int(os.environ.get("UPLOAD_MAX_FILE_SIZE_BYTES", str(10 * 1024 * 1024)))
UPLOAD_ALLOWED_EXTENSIONS = tuple(
    ext.strip().lower()
    for ext in os.environ.get("UPLOAD_ALLOWED_EXTENSIONS", ".jpg,.jpeg,.png,.pdf").split(",")
    if ext.strip()
)
UPLOAD_ALLOWED_CONTENT_TYPES = tuple(
    c.strip().lower()
    for c in os.environ.get(
        "UPLOAD_ALLOWED_CONTENT_TYPES",
        "image/jpeg,image/png,application/pdf",
    ).split(",")
    if c.strip()
)

SPECTACULAR_SETTINGS = {
    "TITLE": "Master Print CRM API",
    "DESCRIPTION": "API for Master Print CRM (staff web app).",
    "VERSION": "0.1.0",
}

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

SMS_PROVIDER = os.environ.get("SMS_PROVIDER", "dummy")
SMS_DRY_RUN = os.environ.get("SMS_DRY_RUN", "1") == "1"

BACKUP_DIR = os.environ.get("BACKUP_DIR", str(BASE_DIR / "backups"))
PII_ENCRYPTION_KEY = os.environ.get("PII_ENCRYPTION_KEY", "")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
