# Generated by Django 5.2.12 on 2026-03-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("users", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("sort_index", models.PositiveIntegerField(default=0)),
                ("is_final", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("sort_index", "id")},
        ),
        migrations.CreateModel(
            name="OrderStatusTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "from_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_from",
                        to="orders.orderstatus",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_to",
                        to="orders.orderstatus",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="orderstatustransition",
            constraint=models.UniqueConstraint(fields=("from_status", "to_status"), name="uq_status_transition"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="", max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="device_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="device_model",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="issue_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="accessories",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="received_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="order",
            name="desired_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="preliminary_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="final_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refusal_mark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="assigned_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.orderstatus",
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
                ("status", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orders.orderstatus")),
            ],
            options={"ordering": ("-changed_at", "-id")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_number"], name="orders_order_order_n_2bb15d_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["received_date"], name="orders_order_received_f5a76e_idx"),
        ),
    ]

