# Generated by Django 5.2.12 on 2026-03-17

from django.db import migrations


def seed_statuses(apps, schema_editor):
    OrderStatus = apps.get_model("orders", "OrderStatus")
    OrderStatusTransition = apps.get_model("orders", "OrderStatusTransition")

    statuses = [
        ("accepted", "Принят", 10, False),
        ("diagnostics", "Диагностика", 20, False),
        ("negotiation", "Согласование", 30, False),
        ("waiting_parts", "Ожидание запчастей", 40, False),
        ("repair", "Ремонт", 50, False),
        ("ready", "Готов", 60, False),
        ("completed", "Выдан", 70, True),
    ]
    by_code = {}
    for code, name, sort_index, is_final in statuses:
        obj, _ = OrderStatus.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "sort_index": sort_index,
                "is_final": is_final,
                "is_active": True,
            },
        )
        by_code[code] = obj

    def add(frm, to):
        OrderStatusTransition.objects.get_or_create(
            from_status=by_code[frm],
            to_status=by_code[to],
            defaults={"is_enabled": True},
        )

    # TЗ 4.1.4 transitions mapped to codes
    add("accepted", "diagnostics")

    add("diagnostics", "negotiation")
    add("diagnostics", "accepted")

    add("negotiation", "waiting_parts")
    add("negotiation", "repair")
    add("negotiation", "accepted")

    add("waiting_parts", "negotiation")
    add("waiting_parts", "accepted")

    add("repair", "ready")
    add("ready", "completed")


def unseed(apps, schema_editor):
    OrderStatus = apps.get_model("orders", "OrderStatus")
    OrderStatusTransition = apps.get_model("orders", "OrderStatusTransition")
    OrderStatusTransition.objects.all().delete()
    OrderStatus.objects.filter(
        code__in=[
            "accepted",
            "diagnostics",
            "negotiation",
            "waiting_parts",
            "repair",
            "ready",
            "completed",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_expand_orders"),
    ]

    operations = [
        migrations.RunPython(seed_statuses, unseed),
    ]

