# Generated by Django 5.2.12 on 2026-03-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_seed_statuses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_order_n_f3ada5_idx',
            old_name='orders_order_order_n_2bb15d_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_receive_8ec391_idx',
            old_name='orders_order_received_f5a76e_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='device_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='issue_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus'),
        ),
    ]
