# Generated by Django 5.2.12 on 2026-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_completed_at_order_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(default='#1A56A3', help_text='CSS hex, e.g. #2563EB', max_length=7),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='visible_to_client',
            field=models.BooleanField(default=True),
        ),
    ]
