# Generated by Django 5.2.12 on 2026-03-22 12:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_finance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='print_order', serialize=False, to='orders.order')),
                ('document_type', models.CharField(max_length=50)),
                ('page_count', models.PositiveIntegerField()),
                ('color_mode', models.CharField(max_length=10)),
                ('urgent', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('file_paths', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'print_orders',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('print', 'Печать')], db_index=True, default='repair', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Дублирует total_amount для обратной совместимости API/отчётов', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_materials_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма продажных цен списанных материалов', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='materials_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Себестоимость материалов (закупка × кол-во)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Прочие затраты по заказу (учитываются в прибыли)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Расчётная прибыль по заказу', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Итого к оплате клиентом', max_digits=12, null=True),
        ),
    ]
