# Generated by Django 5.2.12 on 2026-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
