# Generated by Django 5.2.12 on 2026-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_prophylaxis_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notifications_disabled_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
