# Generated by Django 5.2.12 on 2026-03-27

from django.db import migrations, models
from django.db.models import Q


def _encrypt_existing_client_pii(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    from security.encrypted_fields import encrypt_text, pii_digest

    for client in Client.objects.all().only("id", "phone", "email", "address"):
        phone_plain = client.phone or ""
        email_plain = client.email or ""
        address_plain = client.address or ""
        Client.objects.filter(pk=client.pk).update(
            phone=encrypt_text(phone_plain),
            email=encrypt_text(email_plain),
            address=encrypt_text(address_plain),
            phone_digest=pii_digest(phone_plain),
            email_digest=pii_digest(email_plain),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_last_prophylaxis_reminder_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_digest",
            field=models.CharField(db_index=True, default="", editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="email_digest",
            field=models.CharField(db_index=True, default="", editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(_encrypt_existing_client_pii, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("phone_digest",),
                condition=~Q(phone_digest=""),
                name="uq_clients_phone_digest_non_empty",
            ),
        ),
    ]
