# Generated by Django 5.2.12 on 2026-03-27 08:48

import security.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_encrypt_client_pii'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_phone_164f4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_email_56b9fc_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=security.encrypted_fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=security.encrypted_fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=security.encrypted_fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_digest',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_digest'], name='clients_cli_phone_d_d39dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email_digest'], name='clients_cli_email_d_bd0cdb_idx'),
        ),
    ]
