# Generated by Django 5.2.12 on 2026-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_disabled_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
