# Generated by Django 5.2.12 on 2026-03-17 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'Создан сотрудник'), ('user_updated', 'Изменён сотрудник'), ('user_deleted', 'Удалён сотрудник'), ('user_password_reset', 'Сброшен пароль сотрудника')], max_length=64)),
                ('object_type', models.CharField(blank=True, default='', max_length=128)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
